export const specialties = [
  { name: "All", icon: "Stethoscope" },
  { name: "Internal Medicine", icon: "Stethoscope" },
  { name: "Cardiology", icon: "Heart" },
  { name: "Pediatrics", icon: "Baby" },
  { name: "Neurology", icon: "Brain" },
  { name: "Ophthalmology", icon: "Eye" },
  { name: "Orthopaedics", icon: "User" },
  { name: "Oncology", icon: "Activity" },
  { name: "Obstetrics & Gynaecology", icon: "Heart" },
];

export const hospitals = [
  "All", 
  "Max Super Speciality Hospital, Saket", 
  "Batra Hospital, Tughlakabad", 
  "Indraprastha Apollo Hospital, Sarita Vihar",
  "Max Hospital, Shalimar Bagh", 
  "Max Hospital, Patparganj"
];

export const mockBloodDonors = [
  { id: "bd1", name: "Amit Sharma", bloodType: "O+", phone: "+919810012345", location: "Saket, New Delhi", isAvailable: true },
  { id: "bd2", name: "Priya Verma", bloodType: "A-", phone: "+919910054321", location: "Dwarka Sector 10", isAvailable: true },
  { id: "bd3", name: "Rajesh Gupta", bloodType: "B+", phone: "+919811122233", location: "Rohini, North Delhi", isAvailable: true },
  { id: "bd4", name: "Sneha Kapoor", bloodType: "AB+", phone: "+919818877665", location: "Janakpuri, West Delhi", isAvailable: true },
  { id: "bd5", name: "Vikram Singh", bloodType: "O-", phone: "+919876543210", location: "Vasant Kunj, South Delhi", isAvailable: true },
  { id: "bd6", name: "Anjali Mehra", bloodType: "B-", phone: "+919955443322", location: "Pitampura, New Delhi", isAvailable: true },
  { id: "bd7", name: "Rohan Das", bloodType: "A+", phone: "+919822334455", location: "Karol Bagh, Central Delhi", isAvailable: true },
  { id: "bd8", name: "Sunita Yadav", bloodType: "O+", phone: "+919911223344", location: "Laxmi Nagar, East Delhi", isAvailable: true },
  { id: "bd9", name: "Manish Malhotra", bloodType: "AB-", phone: "+919810101010", location: "Hauz Khas, South Delhi", isAvailable: true },
  { id: "bd10", name: "Kavita Reddy", bloodType: "B+", phone: "+919820202020", location: "Malviya Nagar, New Delhi", isAvailable: true }
];

export const mockAmbulances = [
  { id: "amb1", provider: "Max Healthcare ACLS", location: "Saket", eta: "5 mins", type: "Advanced (Life Support)", phone: "+911126515050" },
  { id: "amb2", provider: "Apollo Critical Care", location: "Sarita Vihar", eta: "8 mins", type: "Advanced (ACLS)", phone: "+911171791090" },
  { id: "amb3", provider: "CAT Government Service", location: "Central Delhi", eta: "12 mins", type: "Basic (BLS)", phone: "102" },
  { id: "amb4", provider: "Private Quick Response", location: "South Delhi", eta: "4 mins", type: "Quick Response (QRT)", phone: "+919810011223" },
];

export const mockDoctors = [
  { 
    id: 1, 
    name: "Dr. Sandeep Budhiraja", 
    specialty: "Internal Medicine", 
    degree: "MBBS, MD (Internal Medicine)",
    experience: 28,
    rating: 4.9, 
    reviews: 450, 
    location: "Max Super Speciality Hospital, Saket", 
    fee: 1500, 
    availability: "Today",
    about: "Group Medical Director at Max Healthcare with extensive experience in managing complex medical cases and infectious diseases."
  },
  { 
    id: 2, 
    name: "Dr. Balbir Singh", 
    specialty: "Cardiology", 
    degree: "MBBS, MD, DM (Cardiology)",
    experience: 35,
    rating: 5.0, 
    reviews: 1200, 
    location: "Max Super Speciality Hospital, Saket", 
    fee: 2000, 
    availability: "Tomorrow",
    about: "Renowned Cardiologist specialized in interventional cardiology, electrophysiology, and complex angioplasties."
  },
  { 
    id: 3, 
    name: "Dr. S. K. Gupta", 
    specialty: "Neurology", 
    degree: "MBBS, MD, DM (Neurology)",
    experience: 32,
    rating: 4.8, 
    reviews: 310, 
    location: "Batra Hospital, Tughlakabad", 
    fee: 1200, 
    availability: "Today",
    about: "Expert in neuro-critical care, stroke management, and epilepsy treatments at Batra Hospital."
  },
  { 
    id: 4, 
    name: "Dr. (Brig) P. K. Tyagi", 
    specialty: "Orthopaedics", 
    degree: "MBBS, MS (Orthopaedics)",
    experience: 40,
    rating: 4.7, 
    reviews: 185, 
    location: "Batra Hospital, Tughlakabad", 
    fee: 1000, 
    availability: "Next Week",
    about: "Former Army Brigadier with decades of experience in trauma surgery, joint replacements, and sports injuries."
  },
  { 
    id: 5, 
    name: "Dr. Archana Dhawan Bajaj", 
    specialty: "Obstetrics & Gynaecology", 
    degree: "MBBS, DGO, DNB",
    experience: 22,
    rating: 4.9, 
    reviews: 640, 
    location: "Max Hospital, Shalimar Bagh", 
    fee: 1500, 
    availability: "Tomorrow",
    about: "Specialized in high-risk pregnancy, IVF, and minimally invasive laparoscopic surgeries."
  },
  { 
    id: 6, 
    name: "Dr. Shakti Bhan Khanna", 
    specialty: "Obstetrics & Gynaecology", 
    degree: "MBBS, MD, FICOG",
    experience: 45,
    rating: 5.0, 
    reviews: 1500, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 2000, 
    availability: "Today",
    about: "Senior Consultant at Apollo Hospitals with over 45 years of experience in Gynaecology and Obstetrics."
  },
  { 
    id: 7, 
    name: "Dr. S.K.S. Marya", 
    specialty: "Orthopaedics", 
    degree: "MBBS, MS, DNB, MCh",
    experience: 38,
    rating: 4.9, 
    reviews: 980, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 2500, 
    availability: "Tomorrow",
    about: "Chairman of Apollo Institute of Orthopaedics, pioneer in joint replacement surgery in India."
  },
  { 
    id: 8, 
    name: "Dr. Nikhil Modi", 
    specialty: "Internal Medicine", 
    degree: "MBBS, MD (Respiratory Medicine)",
    experience: 18,
    rating: 4.7, 
    reviews: 210, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 1200, 
    availability: "Today",
    about: "Expert in pulmonology and critical care, specializing in respiratory tract infections and asthma."
  },
  { 
    id: 9, 
    name: "Dr. Harit Chaturvedi", 
    specialty: "Oncology", 
    degree: "MBBS, MS, MCh (Surgical Oncology)",
    experience: 30,
    rating: 5.0, 
    reviews: 890, 
    location: "Max Super Speciality Hospital, Saket", 
    fee: 2500, 
    availability: "Today",
    about: "Chairman of Max Institute of Cancer Care, internationally recognized for complex cancer surgeries."
  },
  { 
    id: 10, 
    name: "Dr. Sudheer Kumar Tyagi", 
    specialty: "Neurology", 
    degree: "MBBS, MS, MCh (Neurosurgery)",
    experience: 25,
    rating: 4.8, 
    reviews: 340, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 1800, 
    availability: "Next Week",
    about: "Senior Consultant Neurosurgeon with expertise in brain tumor surgery and spine surgery."
  },
  { 
    id: 11, 
    name: "Dr. Sameer Kaul", 
    specialty: "Oncology", 
    degree: "MBBS, MS, MCh (Surgical Oncology)",
    experience: 26,
    rating: 4.9, 
    reviews: 410, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 1500, 
    availability: "Today",
    about: "Specialized in breast and head-neck cancers with over two decades of clinical experience."
  },
  { 
    id: 12, 
    name: "Dr. Anupam Sibal", 
    specialty: "Pediatrics", 
    degree: "MBBS, MD (Pediatrics), MRCP",
    experience: 30,
    rating: 5.0, 
    reviews: 1100, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 2000, 
    availability: "Today",
    about: "Group Medical Director at Apollo Hospitals and a pioneer in pediatric liver transplantation in India."
  },
  { 
    id: 13, 
    name: "Dr. Viney Jetley", 
    specialty: "Cardiology", 
    degree: "MBBS, MD, DM (Cardiology)",
    experience: 25,
    rating: 4.7, 
    reviews: 290, 
    location: "Batra Hospital, Tughlakabad", 
    fee: 1100, 
    availability: "Tomorrow",
    about: "Expert in interventional cardiology with specialization in complex coronary interventions."
  },
  { 
    id: 14, 
    name: "Dr. Rajat Anand", 
    specialty: "Ophthalmology", 
    degree: "MBBS, MS (Ophthalmology)",
    experience: 15,
    rating: 4.6, 
    reviews: 120, 
    location: "Max Super Speciality Hospital, Saket", 
    fee: 800, 
    availability: "Today",
    about: "Specialized in cataract surgery and medical retina with focus on diabetic retinopathy."
  },
  { 
    id: 15, 
    name: "Dr. Meena Chhabra", 
    specialty: "Internal Medicine", 
    degree: "MBBS, MD (General Medicine)",
    experience: 24,
    rating: 4.8, 
    reviews: 560, 
    location: "Max Hospital, Patparganj", 
    fee: 1200, 
    availability: "Tomorrow",
    about: "Expert in metabolic disorders, hypertension, and preventive health screenings."
  },
  { 
    id: 16, 
    name: "Dr. Subrat Akhoury", 
    specialty: "Cardiology", 
    degree: "MBBS, MD, DM (Cardiology)",
    experience: 20,
    rating: 4.9, 
    reviews: 330, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 1800, 
    availability: "Today",
    about: "Senior Interventional Cardiologist with extensive experience in balloon valvuloplasty and pacemaker implantation."
  },
  { 
    id: 17, 
    name: "Dr. B.K. Singh", 
    specialty: "Orthopaedics", 
    degree: "MBBS, MS (Orthopaedics)",
    experience: 27,
    rating: 4.7, 
    reviews: 195, 
    location: "Batra Hospital, Tughlakabad", 
    fee: 1000, 
    availability: "Next Week",
    about: "Specialized in joint replacement, spinal disorders, and pediatric orthopaedics."
  },
  { 
    id: 18, 
    name: "Dr. Neerja Batla", 
    specialty: "Obstetrics & Gynaecology", 
    degree: "MBBS, MD, FICOG",
    experience: 35,
    rating: 5.0, 
    reviews: 2100, 
    location: "Indraprastha Apollo Hospital, Sarita Vihar", 
    fee: 2500, 
    availability: "Tomorrow",
    about: "Pioneer in gynecological oncology and preventive oncology with international recognition."
  }
];
